# Generated by Django 4.1.7 on 2023-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_name_course_description_course_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='photo',
        ),
    ]
