# Generated by Django 4.1.7 on 2023-05-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_remove_course_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=41)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Lession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complete', models.IntegerField()),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
