# Generated by Django 4.1.7 on 2023-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lession_user_lession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_lession',
            old_name='lesion',
            new_name='lession',
        ),
        migrations.AddField(
            model_name='lession',
            name='num',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
