# Generated by Django 4.1.7 on 2023-05-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_lesion_user_lession_lession_lession_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
