# Generated by Django 4.1.7 on 2023-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_duration_course_image_course_mini_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.CharField(default=1, max_length=41),
            preserve_default=False,
        ),
    ]
