# Generated by Django 4.1.7 on 2023-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.CharField(default=1, max_length=41),
            preserve_default=False,
        ),
    ]
